apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo:latest
        volumeMounts:
        - mountPath: /data/db 
          name: mongo-vol
      volumes:
      - name: mongo-vol
        persistentVolumeClaim:  # ✅ Fixed indentation
          claimName: host-pvc  # ✅ Corrected indentation

---
apiVersion: v1
kind: Service
metadata:
  name: service-my-mongo-app
spec:
  selector:
    app: mongo-app
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
